#include<stdio.h>
/*
    ESSA É A BIBLIOTECA PADRÃO DE ENTRADA E SAÍDA DA LINGUAGEM C

    std - STANDARD (PADRÃO)
    i - INPUT (ENTRADA)
    o - OUTPUT (SAÍDA)
    .h - REFERENTE À EXTENSÃO DO ARQUIVO

    AQUI VAMOS ENCONTRAR ALGUMAS FUNÇÕES PARA INSERIR E MOSTRAR DADOS NO PROGRAMA

    POR EXEMPLO, UTILIZAMOS A FUNÇÃO printf(const char) PARA IMPRIMIR TEXTOS OU MOSTRAR
    RESULTADOS DE VARIÁVEIS OU OPERAÇÕES, ONDE const char É UMA CONSTANTE char (VEREMOS
    EM BREVE ESSE E OUTROS TIPOS DE VARIÁVEIS)

    printf("imprimindo um texto qualquer");

    VALE RESSALTAR QUE O PADRÃO DA LINGUAGEM C É EM INGLÊS, ASSIM, OS TEXTOS TEM OS CARACTERES
    DA LÍNGUA INGLESA, OU SEJA, NÃO IRÁ MOSTRAR CARACTERES ESPECIAIS COMO O Ç E ACENTOS
    ESPECIAIS

    PARA REALIZAR A ENTRADA DO PROGRAMA, DEVEMOS UTILIZAR A FUNÇÃO scanf()

    scanf("%X", &variavel);

    X -> UMA LETRA QUE IRÁ DEPENDER DO TIPO DE VARIÁVEL QUE VAMOS ARMAZENAR O CONTEÚDO
    & -> INDICA QUE O CONTEÚDO SERÁ ARMAZENADO NO ENDEREÇO DE MEMÓRIA DA variavel
    variavel -> A VARIÁVEL DEVE TER UM NOME DEFININDO ANTERIORMENTE

    MAIS PRA FRENTE VEREMOS FUNÇÕES SIMILARES E COM FUNCIONALIDADES EXTRAS
*/

#include<stdlib.h>
/*
    A BIBLIOTECA stdlib.h REPRESENTA A BIBLIOTECA PADRÃO DA LINGUAGEM C, ONDE USAREMOS
    ALGUNS COMANDOS

    abs(); -> RETORNA O VALOR ABSOLUTO DE UM NÚMERO INTEIRO
    qsort(); -> FUNÇÃO PARA ORDENAR ELEMENTOS DE UM VETOR
    rand(); -> GERA UM VALOR inteiro ALEATÓRIO
    system(); -> EXECUTA COMANDOS RELACIONADOS AO SISTEMA DO COMPUTADOR 
*/

#include<math.h>
/*
    A BIBLIOTECA math.h É A BIBLIOTECA QUE POSSIBILITA O USO FÁCIL DE FUNÇÕES MATEMÁTICAS,
    COMO POR EXEMPLO:
    
    cos(); -> FUNÇÃO COSSENO
    exp(); -> FUNÇÃO EXPONENCIAL
    log(); -> FUNÇÃO LOGARITMO NATURAL
    log10(); -> FUNÇÃO LOGARITMO NA BASE 10
    pow(); -> FUNÇÃO POTÊNCIA
    round(); -> FUNÇÃO PARA ARREDONDAMENTO DE NÚMEROS REAIS
    sin(); -> FUNÇÃO SENO
    sqrt(); -> FUNÇÃO RAIZ QUADRADA

*/
